{
  "openapi": "3.0.3",
  "info": {
    "title": "JsBattle server API",
    "description": "Internal API of JsBattle ([Swagger File](../api-docs.json))",
    "version": "3.4.1"
  },
  "components": {
    "securitySchemes": {},
    "schemas": {
      "AuthMethods": {
        "type": "object"
      },
      "Battle": {
        "type": "object",
        "required": [
          "createdAt",
          "ubd"
        ],
        "properties": {
          "id": {
            "$ref": "#/components/schemas/entityId"
          },
          "createdAt": {
            "type": "string",
            "format": "date-time"
          },
          "expiresAt": {
            "type": "string",
            "format": "date-time"
          },
          "ubd": {
            "$ref": "#/components/schemas/ubd"
          },
          "description": {
            "type": "string",
            "maxLength": 1024
          },
          "meta": {
            "type": "object"
          },
          "owner": {
            "type": "object",
            "items": {
              "$ref": "#/components/schemas/entityId"
            }
          }
        }
      },
      "Challenge": {
        "type": "object",
        "required": [
          "challengeId",
          "userId",
          "code",
          "modifiedAt",
          "completed"
        ],
        "properties": {
          "id": {
            "$ref": "#/components/schemas/entityId"
          },
          "challengeId": {
            "$ref": "#/components/schemas/entityId"
          },
          "userId": {
            "$ref": "#/components/schemas/entityId"
          },
          "code": {
            "$ref": "#/components/schemas/code"
          },
          "modifiedAt": {
            "type": "string",
            "format": "date-time"
          },
          "completed": {
            "type": "boolean"
          }
        }
      },
      "League": {
        "type": "object",
        "required": [
          "joinedAt",
          "ownerId",
          "ownerName",
          "scriptId",
          "scriptName",
          "fights_total",
          "fights_win",
          "fights_lose",
          "fights_error",
          "score",
          "code"
        ],
        "properties": {
          "id": {
            "$ref": "#/components/schemas/entityId"
          },
          "joinedAt": {
            "type": "string",
            "format": "date-time"
          },
          "ownerId": {
            "$ref": "#/components/schemas/entityId"
          },
          "ownerName": {
            "$ref": "#/components/schemas/entityName"
          },
          "scriptId": {
            "$ref": "#/components/schemas/entityId"
          },
          "scriptName": {
            "$ref": "#/components/schemas/entityName"
          },
          "fights_total": {
            "type": "number",
            "minimum": 0
          },
          "fights_win": {
            "type": "number",
            "minimum": 0
          },
          "fights_lose": {
            "type": "number",
            "minimum": 0
          },
          "fights_error": {
            "type": "number",
            "minimum": 0
          },
          "score": {
            "type": "number",
            "minimum": 0
          },
          "code": {
            "$ref": "#/components/schemas/code"
          },
          "hash": {
            "$ref": "#/components/schemas/hash"
          }
        }
      },
      "LeagueHistory": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "id": {
              "$ref": "#/components/schemas/entityId"
            },
            "createdAt": {
              "type": "string",
              "format": "date-time"
            },
            "players": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "id": {
                    "$ref": "#/components/schemas/entityId"
                  },
                  "name": {
                    "$ref": "#/components/schemas/entityName"
                  },
                  "winner": {
                    "type": "boolean"
                  }
                }
              }
            }
          }
        }
      },
      "LeagueSubmission": {
        "allOf": [
          {
            "$ref": "#/components/schemas/League"
          },
          {
            "type": "object",
            "properties": {
              "latest": {
                "type": "boolean"
              },
              "history": {
                "$ref": "#/components/schemas/LeagueHistory"
              }
            }
          }
        ]
      },
      "LeagueSummary": {
        "type": "object",
        "properties": {
          "submission": {
            "$ref": "#/components/schemas/LeagueSubmission"
          },
          "ranktable": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/League"
            }
          },
          "history": {
            "$ref": "#/components/schemas/LeagueHistory"
          }
        }
      },
      "Script": {
        "type": "object",
        "required": [
          "ownerId",
          "ownerName",
          "scriptName",
          "namespace",
          "code",
          "createdAt",
          "modifiedAt",
          "hash"
        ],
        "properties": {
          "id": {
            "$ref": "#/components/schemas/entityId"
          },
          "ownerId": {
            "$ref": "#/components/schemas/entityId"
          },
          "ownerName": {
            "$ref": "#/components/schemas/entityName"
          },
          "scriptName": {
            "$ref": "#/components/schemas/entityName"
          },
          "namespace": {
            "$ref": "#/components/schemas/entityName"
          },
          "code": {
            "$ref": "#/components/schemas/code"
          },
          "createdAt": {
            "type": "string",
            "format": "date-time"
          },
          "modifiedAt": {
            "type": "string",
            "format": "date-time"
          },
          "hash": {
            "$ref": "#/components/schemas/hash"
          }
        }
      },
      "User": {
        "type": "object",
        "required": [
          "username",
          "provider",
          "extUserId",
          "role",
          "createdAt",
          "lastLoginAt"
        ],
        "properties": {
          "id": {
            "$ref": "#/components/schemas/entityId"
          },
          "username": {
            "$ref": "#/components/schemas/entityName"
          },
          "displayName": {
            "type": "string",
            "minLength": 3,
            "maxLength": 32,
            "pattern": "^[A-Za-z0-9\\- .]+$"
          },
          "provider": {
            "$ref": "#/components/schemas/entityName"
          },
          "extUserId": {
            "type": "string",
            "minLength": 1,
            "maxLength": 1024
          },
          "email": {
            "$ref": "#/components/schemas/email"
          },
          "registered": {
            "type": "boolean"
          },
          "role": {
            "$ref": "#/components/schemas/entityName"
          },
          "createdAt": {
            "type": "string",
            "format": "date-time"
          },
          "lastLoginAt": {
            "type": "string",
            "format": "date-time"
          }
        }
      },
      "UserInitData": {
        "type": "object",
        "properties": {
          "username": {
            "$ref": "#/components/schemas/entityName"
          },
          "displayName": {
            "type": "string",
            "minLength": 3,
            "maxLength": 32,
            "pattern": "^[A-Za-z0-9\\- .]+$"
          },
          "challenges": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "challengeId": {
                  "$ref": "#/components/schemas/entityId"
                },
                "completed": {
                  "type": "boolean"
                },
                "code": {
                  "$ref": "#/components/schemas/code"
                }
              }
            }
          },
          "scripts": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "scriptName": {
                  "$ref": "#/components/schemas/entityName"
                },
                "code": {
                  "$ref": "#/components/schemas/code"
                }
              }
            }
          }
        }
      },
      "code": {
        "type": "string",
        "maxLength": 65536
      },
      "email": {
        "type": "string",
        "maxLength": 256,
        "pattern": "^([\\w-]+@([\\w-]+\\.)+[\\w-]+)|$"
      },
      "entityId": {
        "type": "string",
        "minLength": 3,
        "maxLength": 64,
        "pattern": "^[A-Za-z0-9_\\-.\\\\]+$"
      },
      "entityName": {
        "type": "string",
        "minLength": 3,
        "maxLength": 16,
        "pattern": "^[A-Za-z0-9_-]+$"
      },
      "hash": {
        "type": "string",
        "minLength": 16,
        "maxLength": 128,
        "pattern": "^[a-zA-Z0-9]+$"
      },
      "ubd": {
        "type": "string",
        "minLength": 2,
        "maxLength": 524288
      }
    },
    "examples": {
      "AuthMethods": {
        "value": {
          "github": {
            "name": "GitHub",
            "url": "http://localhost:9000/auth/github"
          },
          "google": {
            "name": "Google",
            "url": "http://localhost:9000/auth/google"
          }
        }
      },
      "Battle": {
        "value": {
          "id": "5f002352d7075d564ec03048",
          "createdAt": "2020-07-04T06:36:02.048Z",
          "expiresAt": "2020-07-05T18:36:02.048Z",
          "ubd": "{\"foo\": \"bar\"}",
          "description": "jsbattle/sniper vs jsbattle/crawler",
          "meta": [
            {
              "id": "5ee5f5ab15fc3f3f278082c4",
              "name": "jsbattle/sniper",
              "winner": true
            },
            {
              "id": "5ee698c99feda049511a15ee",
              "name": "jsbattle/crawler",
              "winner": false
            }
          ],
          "owner": [
            "5ee5f5ab15fc3f3f278082c4",
            "5ee698c99feda049511a15ee"
          ]
        }
      },
      "Challenge": {
        "value": {
          "id": "a2d7075d56b76c234ec03048",
          "userId": "07ec06a685d56ba2d787af44",
          "challengeId": "challenge-8UCUaNvC",
          "modifiedAt": "2020-07-05T18:36:02.048Z",
          "code": "console.log('hello world')",
          "completed": false
        }
      },
      "Challenge_update": {
        "value": {
          "code": "console.log('hello world')",
          "completed": false
        }
      },
      "Challenge_list": {
        "value": [
          {
            "challengeId": "challenge-8UCUaNvC",
            "completed": true
          },
          {
            "challengeId": "challenge-Du7tyrCB",
            "completed": true
          },
          {
            "challengeId": "challenge-4syTf6ph",
            "completed": false
          }
        ]
      },
      "League": {
        "value": {
          "id": "a2d7075d56b76c234ec03048",
          "jonedAt": "2020-07-05T18:36:02.048Z",
          "ownerId": "07ec06a685d56ba2d787af44",
          "ownerName": "johnny",
          "scriptId": "587ab58706a685daf4407e1",
          "scriptName": "bravo",
          "fights_total": 109,
          "fights_win": 62,
          "fights_lose": 47,
          "fights_error": 0,
          "score": 5688,
          "code": "console.log('hello world')",
          "hash": "4D2B0403F1CC1B465C69814AA49AF1A86A9094FA"
        }
      },
      "League_join": {
        "value": {
          "scriptId": "587ab58706a685daf4407e1"
        }
      },
      "LeagueHistory": {
        "value": [
          {
            "id": "ztYTcUTDOE5g9doS",
            "createdAt": "2020-07-05T07:14:20.509Z",
            "players": [
              {
                "id": "pXgkeRXuPI3AxggE",
                "name": "jsbattle/chicken",
                "winner": true
              },
              {
                "id": "dLz6Nz8lLmmlvzUT",
                "name": "jsbattle/crawler",
                "winner": false
              }
            ]
          },
          {
            "id": "TSRqYpMO61okgWbJ",
            "createdAt": "2020-07-05T07:14:14.531Z",
            "players": [
              {
                "id": "c8P3GlLUD5IPKYi4",
                "name": "jsbattle/sniper",
                "winner": false
              },
              {
                "id": "JYoJCbKQWX6oxZC4",
                "name": "jsbattle/jamro",
                "winner": true
              }
            ]
          }
        ]
      },
      "LeagueSubmission": {
        "value": {
          "allOf": [
            {
              "$ref": "#/components/examples/League/value"
            },
            {
              "latest": true,
              "history": [
                {
                  "$ref": "#/components/examples/LeagueHistory/value/0"
                }
              ]
            }
          ]
        }
      },
      "LeagueSummary": {
        "value": {
          "submission": {
            "$ref": "#/components/examples/LeagueSubmission/value"
          },
          "ranktable": [
            {
              "$ref": "#/components/examples/League/value"
            }
          ],
          "history": [
            {
              "$ref": "#/components/examples/LeagueHistory/value/0"
            }
          ]
        }
      },
      "LeagueSummary_empty": {
        "value": {
          "submission": {},
          "ranktable": [
            {
              "$ref": "#/components/examples/League/value"
            }
          ],
          "history": [
            {
              "$ref": "#/components/examples/LeagueHistory/value/0"
            }
          ]
        }
      },
      "Script": {
        "value": {
          "id": "81d7075d564e3e403fc07621",
          "ownerId": "5d564ec076351f082a81d707",
          "ownerName": "johnny",
          "scriptName": "bravo",
          "namespace": "user",
          "code": "console.log('hello world')",
          "createdAt": "2020-07-04T06:36:02.048Z",
          "modifiedAt": "2020-07-04T06:39:42.184Z",
          "hash": "4D2B0403F1CC1B465C69814AA49AF1A86A9094FA"
        }
      },
      "Script_update": {
        "value": {
          "scriptName": "bravo",
          "code": "console.log('hello world')"
        }
      },
      "Script_list": {
        "value": [
          {
            "id": "81d7075d564e3e403fc07621",
            "ownerId": "5d564ec076351f082a81d707",
            "ownerName": "johnny",
            "scriptName": "bravo",
            "namespace": "user",
            "code": "console.log('hello world')",
            "createdAt": "2020-07-04T06:36:02.048Z",
            "modifiedAt": "2020-07-04T06:39:42.184Z",
            "hash": "4D2B0403F1CC1B465C69814AA49AF1A86A9094FA"
          },
          {
            "id": "0703f62181de3e475d5c0764",
            "ownerId": "5d564ec076351f082a81d707",
            "ownerName": "johnny",
            "scriptName": "predator",
            "namespace": "user",
            "code": "console.log('hello world 2')",
            "createdAt": "2020-07-05T11:32:12.001Z",
            "modifiedAt": "2020-07-06T12:19:54.938Z",
            "hash": "F1A840696A93F1CC09812B01B4654AA49A4FA4DC"
          }
        ]
      },
      "User": {
        "value": {
          "id": "81d7075d564e3e403fc07621",
          "username": "johnny",
          "displayName": "Johnny Bravo",
          "provider": "google",
          "extUserId": "johny.bravo",
          "email": "johny.bravo@example.com",
          "registered": true,
          "role": "user",
          "createdAt": "2020-07-04T06:36:02.048Z",
          "lastLoginAt": "2020-07-04T05:41:19.932Z"
        }
      },
      "User_guest": {
        "value": {
          "username": "guest",
          "displayName": "Guest",
          "provider": "",
          "extUserId": "",
          "email": "",
          "registered": false,
          "role": "guest",
          "createdAt": "2020-07-04T20:33:11.725Z",
          "lastLoginAt": "2020-07-04T20:33:11.725Z"
        }
      },
      "UserInitData": {
        "value": {
          "username": "johnny",
          "displayName": "Johnny Bravo",
          "challenges": [
            {
              "challengeId": "challenge-8UCUaNvC",
              "code": "console.log(\"hello world\")",
              "completed": false
            }
          ],
          "scripts": [
            {
              "scriptName": "alpha",
              "code": "console.log(\"hello world from alpha\")"
            }
          ]
        }
      },
      "code": {
        "value": "console.log('hello wolrd');"
      },
      "email": {
        "value": "johny.bravo@example.com"
      },
      "entityId": {
        "value": "MRF6IRZb2CKYk8Ie"
      },
      "entityName": {
        "value": "bravo"
      },
      "hash_deafult": {
        "value": "9AF1A86A4DC1B465C69814AA49094FA2B0403F1C"
      },
      "ubd": {
        "value": "{\"foo\": \"bar\"}"
      }
    }
  },
  "paths": {
    "/api/profile": {
      "get": {
        "tags": [
          "account"
        ],
        "description": "Information about current user",
        "responses": {
          "200": {
            "description": "a successfull response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                },
                "examples": {
                  "user": {
                    "$ref": "#/components/examples/User"
                  },
                  "guest": {
                    "$ref": "#/components/examples/User_guest"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/authMethods": {
      "get": {
        "tags": [
          "account"
        ],
        "description": "List of supported authentication methods",
        "responses": {
          "200": {
            "description": "a successfull response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AuthMethods"
                },
                "examples": {
                  "default": {
                    "$ref": "#/components/examples/AuthMethods"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/leaguePreview": {
      "get": {
        "tags": [
          "league"
        ],
        "description": "history of recent league battles",
        "responses": {
          "200": {
            "description": "a successfull response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LeagueHistory"
                },
                "examples": {
                  "default": {
                    "$ref": "#/components/examples/LeagueHistory"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/leaguePreview/replay/{battleId}": {
      "get": {
        "tags": [
          "league"
        ],
        "description": "replay of league battle",
        "parameters": [
          {
            "in": "path",
            "name": "battleId",
            "description": "ID of the battle",
            "required": true,
            "schema": {
              "$ref": "#/components/schemas/entityId"
            },
            "examples": {
              "default": {
                "$ref": "#/components/examples/entityId"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "a successfull response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Battle"
                },
                "examples": {
                  "default": {
                    "$ref": "#/components/examples/Battle"
                  }
                }
              }
            }
          },
          "404": {
            "description": "battle with provided Id does not exist"
          }
        }
      }
    },
    "/api/user/initData": {
      "patch": {
        "tags": [
          "account"
        ],
        "description": "user data used during registration to transit progress from un registered to registered user",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UserInitData"
              },
              "examples": {
                "default": {
                  "$ref": "#/components/examples/UserInitData"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "a successfull response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                },
                "examples": {
                  "default": {
                    "$ref": "#/components/examples/User"
                  }
                }
              }
            }
          },
          "401": {
            "description": "not authorized"
          },
          "422": {
            "description": "user already registered"
          }
        },
        "security": [
          {
            "oauth_default": []
          }
        ]
      }
    },
    "/api/user/scripts": {
      "get": {
        "tags": [
          "scripts"
        ],
        "description": "list all scripts of current user",
        "responses": {
          "200": {
            "description": "a successfull response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Script"
                  }
                },
                "examples": {
                  "default": {
                    "$ref": "#/components/examples/Script_list"
                  }
                }
              }
            }
          },
          "401": {
            "description": "not authorized"
          }
        },
        "security": [
          {
            "oauth_default": []
          }
        ]
      },
      "post": {
        "tags": [
          "scripts"
        ],
        "description": "create a new script owned by currrent user.",
        "responses": {
          "200": {
            "description": "a successfull response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Script"
                },
                "examples": {
                  "default": {
                    "$ref": "#/components/examples/Script"
                  }
                }
              }
            }
          },
          "401": {
            "description": "not authorized"
          },
          "422": {
            "description": "script limit exceeded"
          }
        },
        "security": [
          {
            "oauth_default": []
          }
        ]
      }
    },
    "/api/user/scripts/{scriptId}": {
      "get": {
        "tags": [
          "scripts"
        ],
        "description": "a script owned by currrent user",
        "parameters": [
          {
            "in": "path",
            "name": "scriptId",
            "description": "ID of the script",
            "required": true,
            "schema": {
              "$ref": "#/components/schemas/entityId"
            },
            "examples": {
              "default": {
                "$ref": "#/components/examples/entityId"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "a successfull response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Script"
                },
                "examples": {
                  "default": {
                    "$ref": "#/components/examples/Script"
                  }
                }
              }
            }
          },
          "401": {
            "description": "not authorized"
          },
          "404": {
            "description": "script not found"
          }
        },
        "security": [
          {
            "oauth_default": []
          }
        ]
      },
      "patch": {
        "tags": [
          "scripts"
        ],
        "description": "update a script owned by currrent user",
        "parameters": [
          {
            "in": "path",
            "name": "scriptId",
            "description": "ID of the script",
            "required": true,
            "schema": {
              "$ref": "#/components/schemas/entityId"
            },
            "examples": {
              "default": {
                "$ref": "#/components/examples/entityId"
              }
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Script"
              },
              "examples": {
                "default": {
                  "$ref": "#/components/examples/Script_update"
                }
              }
            }
          },
          "description": "Script object to be updated",
          "required": true
        },
        "responses": {
          "200": {
            "description": "a successfull response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Script"
                },
                "examples": {
                  "default": {
                    "$ref": "#/components/examples/Script"
                  }
                }
              }
            }
          },
          "401": {
            "description": "not authorized"
          },
          "404": {
            "description": "script not found"
          }
        },
        "security": [
          {
            "oauth_default": []
          }
        ]
      },
      "delete": {
        "tags": [
          "scripts"
        ],
        "description": "remove a script owned by currrent user",
        "parameters": [
          {
            "in": "path",
            "name": "scriptId",
            "description": "ID of the script",
            "required": true,
            "schema": {
              "$ref": "#/components/schemas/entityId"
            },
            "examples": {
              "default": {
                "$ref": "#/components/examples/entityId"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "a successfull response"
          },
          "401": {
            "description": "not authorized"
          },
          "404": {
            "description": "script not found"
          }
        },
        "security": [
          {
            "oauth_default": []
          }
        ]
      }
    },
    "/api/user/challenges": {
      "get": {
        "tags": [
          "challenges"
        ],
        "description": "challenges of current user",
        "responses": {
          "200": {
            "description": "a successfull response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Challenge"
                  }
                },
                "examples": {
                  "default": {
                    "$ref": "#/components/examples/Challenge_list"
                  }
                }
              }
            }
          },
          "401": {
            "description": "not authorized"
          }
        },
        "security": [
          {
            "oauth_default": []
          }
        ]
      }
    },
    "/api/user/challenges/{challengeId}": {
      "get": {
        "tags": [
          "challenges"
        ],
        "description": "specific challenge of  current user",
        "parameters": [
          {
            "in": "path",
            "name": "challengeId",
            "description": "ID of the challenge",
            "required": true,
            "schema": {
              "$ref": "#/components/schemas/entityId"
            },
            "examples": {
              "default": {
                "$ref": "#/components/examples/entityId"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "a successfull response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Challenge"
                },
                "examples": {
                  "default": {
                    "$ref": "#/components/examples/Challenge"
                  }
                }
              }
            }
          },
          "401": {
            "description": "not authorized"
          },
          "404": {
            "description": "challenge not found"
          }
        },
        "security": [
          {
            "oauth_default": []
          }
        ]
      },
      "patch": {
        "tags": [
          "challenges"
        ],
        "description": "update specific challenge of  current user",
        "parameters": [
          {
            "in": "path",
            "name": "challengeId",
            "description": "ID of the challenge",
            "required": true,
            "schema": {
              "$ref": "#/components/schemas/entityId"
            },
            "examples": {
              "default": {
                "$ref": "#/components/examples/entityId"
              }
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Challenge"
              },
              "examples": {
                "default": {
                  "$ref": "#/components/examples/Challenge_update"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "a successfull response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Challenge"
                },
                "examples": {
                  "default": {
                    "$ref": "#/components/examples/Challenge"
                  }
                }
              }
            }
          },
          "401": {
            "description": "not authorized"
          },
          "404": {
            "description": "challenge not found"
          }
        },
        "security": [
          {
            "oauth_default": []
          }
        ]
      }
    },
    "/api/user/league": {
      "get": {
        "tags": [
          "league"
        ],
        "description": "league summary for current user",
        "responses": {
          "200": {
            "description": "a successfull response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LeagueSummary"
                },
                "examples": {
                  "default": {
                    "$ref": "#/components/examples/LeagueSummary"
                  }
                }
              }
            }
          },
          "401": {
            "description": "not authorized"
          }
        },
        "security": [
          {
            "oauth_default": []
          }
        ]
      }
    },
    "/api/user/league/replay/{battleId}": {
      "get": {
        "tags": [
          "league"
        ],
        "description": "replay of league battle",
        "parameters": [
          {
            "in": "path",
            "name": "battleId",
            "description": "ID of the battle",
            "required": true,
            "schema": {
              "$ref": "#/components/schemas/entityId"
            },
            "examples": {
              "default": {
                "$ref": "#/components/examples/entityId"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "a successfull response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Battle"
                },
                "examples": {
                  "default": {
                    "$ref": "#/components/examples/Battle"
                  }
                }
              }
            }
          },
          "401": {
            "description": "not authorized"
          },
          "404": {
            "description": "battle with provided Id does not exist"
          }
        },
        "security": [
          {
            "oauth_default": []
          }
        ]
      }
    },
    "/api/user/league/submission": {
      "get": {
        "tags": [
          "league"
        ],
        "description": "current user submission to the league",
        "responses": {
          "200": {
            "description": "a successfull response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LeagueSubmission"
                },
                "examples": {
                  "default": {
                    "$ref": "#/components/examples/LeagueSubmission"
                  }
                }
              }
            }
          },
          "401": {
            "description": "not authorized"
          }
        },
        "security": [
          {
            "oauth_default": []
          }
        ]
      },
      "patch": {
        "tags": [
          "league"
        ],
        "description": "join or re-join the league by current user",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/League"
              },
              "examples": {
                "default": {
                  "$ref": "#/components/examples/League_join"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "a successfull response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LeagueSummary"
                },
                "examples": {
                  "default": {
                    "$ref": "#/components/examples/LeagueSummary"
                  }
                }
              }
            }
          },
          "401": {
            "description": "not authorized"
          }
        },
        "security": [
          {
            "oauth_default": []
          }
        ]
      },
      "delete": {
        "tags": [
          "league"
        ],
        "description": "leave the league by current user",
        "responses": {
          "200": {
            "description": "a successfull response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LeagueSummary"
                },
                "examples": {
                  "default": {
                    "$ref": "#/components/examples/LeagueSummary_empty"
                  }
                }
              }
            }
          },
          "401": {
            "description": "not authorized"
          }
        },
        "security": [
          {
            "oauth_default": []
          }
        ]
      }
    },
    "/api/user/league/ranktable": {
      "get": {
        "tags": [
          "league"
        ],
        "description": "rank table slice for current user",
        "responses": {
          "200": {
            "description": "a successfull response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/League"
                  }
                },
                "examples": {
                  "default": {
                    "value": [
                      {
                        "$ref": "#/components/examples/League/value"
                      }
                    ]
                  }
                }
              }
            }
          },
          "401": {
            "description": "not authorized"
          }
        },
        "security": [
          {
            "oauth_default": []
          }
        ]
      }
    },
    "/api/user/league/scripts/{scriptId}": {
      "get": {
        "tags": [
          "league"
        ],
        "description": "script from submission to the league",
        "parameters": [
          {
            "in": "path",
            "name": "scriptId",
            "description": "ID of the script",
            "required": true,
            "schema": {
              "$ref": "#/components/schemas/entityId"
            },
            "examples": {
              "default": {
                "$ref": "#/components/examples/entityId"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "a successfull response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Script"
                },
                "examples": {
                  "default": {
                    "$ref": "#/components/examples/Script"
                  }
                }
              }
            }
          },
          "401": {
            "description": "not authorized"
          },
          "404": {
            "description": "script not found"
          }
        },
        "security": [
          {
            "oauth_default": []
          }
        ]
      }
    }
  },
  "tags": []
}
